### ISSUE TITLE
Game Assets

### ISSUE THREAD

**Issue by AiGreoh** [ProgrammingPhilippines/project_rei#14]
Below is the list of all assets that were conceptualized (may add new list occasionally, so stay tuned!)

**ASSETS**
➤ _Models_
- Discord User Model
- Discord Raiders Model (Both Dark and Light Discord Raiders)
- Thy Box (Including its simple walls and debris)
- Weapons (`The Silencer`, `Ban Gun` and `Ban Hammer`. This includes the explosives.)
- Currency Collectibles (`NitroCoin` and `NitroGem`)

➤ _Sound and Music_
- Weapons (`The Silencer Upon Shoot`, `Ban Gun Upon Shoot` and `Ban Hammer Upon Swing`. This includes the explosives' kaboom.) `.wav`
- Discord User Mode Upon Hurt `.wav`
- Discord Raiders Model Upon Hurt `.wav`
- Shop Upon Arrival `.mp3`
- Game Over `.mp3`
- Start Menu `.mp3`
- Thy Box `.mp3`

**Comment by hddnblde** [comment]
@AiGreoh please plan out and include our requirements for UI, we'll need just the basics first (Title Screen, Actual Game Screen, Game Over Screen, and possible Shop UI)

@desuchan27 re: UI, please collab with Greoh for this

@ianaumi start thinking about music, as for sfx you can download free assets for this

Cheers!
